// <auto-generated>
//     Generated from ShapeCatalogService.EnumerateCatalog() - do not edit by hand.
//     Regenerate from the ShapeGeneratorSettingsScriptable asset in the Unity project.
// </auto-generated>

using BH.SDK.Utils;

namespace BH.SDK.Models.Primitives
{
    public partial struct ShapeId
    {
        /// <summary> Square - 6 shapes. </summary>
        public static class Square
        {
            public static readonly ShapeId Fill = new(GuidHelper.FromIntAtEnd(0x01000));
            public static readonly ShapeId T2   = new(GuidHelper.FromIntAtEnd(0x01001));
            public static readonly ShapeId T4   = new(GuidHelper.FromIntAtEnd(0x01002));
            public static readonly ShapeId T8   = new(GuidHelper.FromIntAtEnd(0x01003));
            public static readonly ShapeId T16  = new(GuidHelper.FromIntAtEnd(0x01004));
            public static readonly ShapeId T32  = new(GuidHelper.FromIntAtEnd(0x01005));
        }

        /// <summary> Circle - 48 shapes. </summary>
        public static class Circle
        {
            public static readonly ShapeId Fill     = new(GuidHelper.FromIntAtEnd(0x02000));
            public static readonly ShapeId I        = new(GuidHelper.FromIntAtEnd(0x102000));
            public static readonly ShapeId T2       = new(GuidHelper.FromIntAtEnd(0x02001));
            public static readonly ShapeId T2_I     = new(GuidHelper.FromIntAtEnd(0x102001));
            public static readonly ShapeId T4       = new(GuidHelper.FromIntAtEnd(0x02002));
            public static readonly ShapeId T4_I     = new(GuidHelper.FromIntAtEnd(0x102002));
            public static readonly ShapeId T8       = new(GuidHelper.FromIntAtEnd(0x02003));
            public static readonly ShapeId T8_I     = new(GuidHelper.FromIntAtEnd(0x102003));
            public static readonly ShapeId T16      = new(GuidHelper.FromIntAtEnd(0x02004));
            public static readonly ShapeId T16_I    = new(GuidHelper.FromIntAtEnd(0x102004));
            public static readonly ShapeId T32      = new(GuidHelper.FromIntAtEnd(0x02005));
            public static readonly ShapeId T32_I    = new(GuidHelper.FromIntAtEnd(0x102005));
            public static readonly ShapeId S2       = new(GuidHelper.FromIntAtEnd(0x02010));
            public static readonly ShapeId S2_I     = new(GuidHelper.FromIntAtEnd(0x102010));
            public static readonly ShapeId S2_T2    = new(GuidHelper.FromIntAtEnd(0x02011));
            public static readonly ShapeId S2_T2_I  = new(GuidHelper.FromIntAtEnd(0x102011));
            public static readonly ShapeId S2_T4    = new(GuidHelper.FromIntAtEnd(0x02012));
            public static readonly ShapeId S2_T4_I  = new(GuidHelper.FromIntAtEnd(0x102012));
            public static readonly ShapeId S2_T8    = new(GuidHelper.FromIntAtEnd(0x02013));
            public static readonly ShapeId S2_T8_I  = new(GuidHelper.FromIntAtEnd(0x102013));
            public static readonly ShapeId S2_T16   = new(GuidHelper.FromIntAtEnd(0x02014));
            public static readonly ShapeId S2_T16_I = new(GuidHelper.FromIntAtEnd(0x102014));
            public static readonly ShapeId S2_T32   = new(GuidHelper.FromIntAtEnd(0x02015));
            public static readonly ShapeId S2_T32_I = new(GuidHelper.FromIntAtEnd(0x102015));
            public static readonly ShapeId S4       = new(GuidHelper.FromIntAtEnd(0x02020));
            public static readonly ShapeId S4_I     = new(GuidHelper.FromIntAtEnd(0x102020));
            public static readonly ShapeId S4_T2    = new(GuidHelper.FromIntAtEnd(0x02021));
            public static readonly ShapeId S4_T2_I  = new(GuidHelper.FromIntAtEnd(0x102021));
            public static readonly ShapeId S4_T4    = new(GuidHelper.FromIntAtEnd(0x02022));
            public static readonly ShapeId S4_T4_I  = new(GuidHelper.FromIntAtEnd(0x102022));
            public static readonly ShapeId S4_T8    = new(GuidHelper.FromIntAtEnd(0x02023));
            public static readonly ShapeId S4_T8_I  = new(GuidHelper.FromIntAtEnd(0x102023));
            public static readonly ShapeId S4_T16   = new(GuidHelper.FromIntAtEnd(0x02024));
            public static readonly ShapeId S4_T16_I = new(GuidHelper.FromIntAtEnd(0x102024));
            public static readonly ShapeId S4_T32   = new(GuidHelper.FromIntAtEnd(0x02025));
            public static readonly ShapeId S4_T32_I = new(GuidHelper.FromIntAtEnd(0x102025));
            public static readonly ShapeId S8       = new(GuidHelper.FromIntAtEnd(0x02030));
            public static readonly ShapeId S8_I     = new(GuidHelper.FromIntAtEnd(0x102030));
            public static readonly ShapeId S8_T2    = new(GuidHelper.FromIntAtEnd(0x02031));
            public static readonly ShapeId S8_T2_I  = new(GuidHelper.FromIntAtEnd(0x102031));
            public static readonly ShapeId S8_T4    = new(GuidHelper.FromIntAtEnd(0x02032));
            public static readonly ShapeId S8_T4_I  = new(GuidHelper.FromIntAtEnd(0x102032));
            public static readonly ShapeId S8_T8    = new(GuidHelper.FromIntAtEnd(0x02033));
            public static readonly ShapeId S8_T8_I  = new(GuidHelper.FromIntAtEnd(0x102033));
            public static readonly ShapeId S8_T16   = new(GuidHelper.FromIntAtEnd(0x02034));
            public static readonly ShapeId S8_T16_I = new(GuidHelper.FromIntAtEnd(0x102034));
            public static readonly ShapeId S8_T32   = new(GuidHelper.FromIntAtEnd(0x02035));
            public static readonly ShapeId S8_T32_I = new(GuidHelper.FromIntAtEnd(0x102035));
        }

        /// <summary> RightTriangle - 11 shapes. </summary>
        public static class RightTriangle
        {
            public static readonly ShapeId Fill  = new(GuidHelper.FromIntAtEnd(0x03000));
            public static readonly ShapeId T2    = new(GuidHelper.FromIntAtEnd(0x03001));
            public static readonly ShapeId T2_I  = new(GuidHelper.FromIntAtEnd(0x103001));
            public static readonly ShapeId T4    = new(GuidHelper.FromIntAtEnd(0x03002));
            public static readonly ShapeId T4_I  = new(GuidHelper.FromIntAtEnd(0x103002));
            public static readonly ShapeId T8    = new(GuidHelper.FromIntAtEnd(0x03003));
            public static readonly ShapeId T8_I  = new(GuidHelper.FromIntAtEnd(0x103003));
            public static readonly ShapeId T16   = new(GuidHelper.FromIntAtEnd(0x03004));
            public static readonly ShapeId T16_I = new(GuidHelper.FromIntAtEnd(0x103004));
            public static readonly ShapeId T32   = new(GuidHelper.FromIntAtEnd(0x03005));
            public static readonly ShapeId T32_I = new(GuidHelper.FromIntAtEnd(0x103005));
        }

        /// <summary> Triangle - 12 shapes. </summary>
        public static class Triangle
        {
            public static readonly ShapeId Fill  = new(GuidHelper.FromIntAtEnd(0x04000));
            public static readonly ShapeId I     = new(GuidHelper.FromIntAtEnd(0x104000));
            public static readonly ShapeId T2    = new(GuidHelper.FromIntAtEnd(0x04001));
            public static readonly ShapeId T2_I  = new(GuidHelper.FromIntAtEnd(0x104001));
            public static readonly ShapeId T4    = new(GuidHelper.FromIntAtEnd(0x04002));
            public static readonly ShapeId T4_I  = new(GuidHelper.FromIntAtEnd(0x104002));
            public static readonly ShapeId T8    = new(GuidHelper.FromIntAtEnd(0x04003));
            public static readonly ShapeId T8_I  = new(GuidHelper.FromIntAtEnd(0x104003));
            public static readonly ShapeId T16   = new(GuidHelper.FromIntAtEnd(0x04004));
            public static readonly ShapeId T16_I = new(GuidHelper.FromIntAtEnd(0x104004));
            public static readonly ShapeId T32   = new(GuidHelper.FromIntAtEnd(0x04005));
            public static readonly ShapeId T32_I = new(GuidHelper.FromIntAtEnd(0x104005));
        }

        /// <summary> Pentagon - 48 shapes. </summary>
        public static class Pentagon
        {
            public static readonly ShapeId Fill       = new(GuidHelper.FromIntAtEnd(0x15000));
            public static readonly ShapeId I          = new(GuidHelper.FromIntAtEnd(0x115000));
            public static readonly ShapeId T2         = new(GuidHelper.FromIntAtEnd(0x15001));
            public static readonly ShapeId T2_I       = new(GuidHelper.FromIntAtEnd(0x115001));
            public static readonly ShapeId T4         = new(GuidHelper.FromIntAtEnd(0x15002));
            public static readonly ShapeId T4_I       = new(GuidHelper.FromIntAtEnd(0x115002));
            public static readonly ShapeId T8         = new(GuidHelper.FromIntAtEnd(0x15003));
            public static readonly ShapeId T8_I       = new(GuidHelper.FromIntAtEnd(0x115003));
            public static readonly ShapeId T16        = new(GuidHelper.FromIntAtEnd(0x15004));
            public static readonly ShapeId T16_I      = new(GuidHelper.FromIntAtEnd(0x115004));
            public static readonly ShapeId T32        = new(GuidHelper.FromIntAtEnd(0x15005));
            public static readonly ShapeId T32_I      = new(GuidHelper.FromIntAtEnd(0x115005));
            public static readonly ShapeId S2         = new(GuidHelper.FromIntAtEnd(0x15010));
            public static readonly ShapeId S2_I       = new(GuidHelper.FromIntAtEnd(0x115010));
            public static readonly ShapeId S2_T2      = new(GuidHelper.FromIntAtEnd(0x15011));
            public static readonly ShapeId S2_T2_I    = new(GuidHelper.FromIntAtEnd(0x115011));
            public static readonly ShapeId S2_T4      = new(GuidHelper.FromIntAtEnd(0x15012));
            public static readonly ShapeId S2_T4_I    = new(GuidHelper.FromIntAtEnd(0x115012));
            public static readonly ShapeId S2_T8      = new(GuidHelper.FromIntAtEnd(0x15013));
            public static readonly ShapeId S2_T8_I    = new(GuidHelper.FromIntAtEnd(0x115013));
            public static readonly ShapeId S2_T16     = new(GuidHelper.FromIntAtEnd(0x15014));
            public static readonly ShapeId S2_T16_I   = new(GuidHelper.FromIntAtEnd(0x115014));
            public static readonly ShapeId S2_T32     = new(GuidHelper.FromIntAtEnd(0x15015));
            public static readonly ShapeId S2_T32_I   = new(GuidHelper.FromIntAtEnd(0x115015));
            public static readonly ShapeId S4         = new(GuidHelper.FromIntAtEnd(0x15020));
            public static readonly ShapeId S4_I       = new(GuidHelper.FromIntAtEnd(0x115020));
            public static readonly ShapeId S4_T2      = new(GuidHelper.FromIntAtEnd(0x15021));
            public static readonly ShapeId S4_T2_I    = new(GuidHelper.FromIntAtEnd(0x115021));
            public static readonly ShapeId S4_T4      = new(GuidHelper.FromIntAtEnd(0x15022));
            public static readonly ShapeId S4_T4_I    = new(GuidHelper.FromIntAtEnd(0x115022));
            public static readonly ShapeId S4_T8      = new(GuidHelper.FromIntAtEnd(0x15023));
            public static readonly ShapeId S4_T8_I    = new(GuidHelper.FromIntAtEnd(0x115023));
            public static readonly ShapeId S4_T16     = new(GuidHelper.FromIntAtEnd(0x15024));
            public static readonly ShapeId S4_T16_I   = new(GuidHelper.FromIntAtEnd(0x115024));
            public static readonly ShapeId S4_T32     = new(GuidHelper.FromIntAtEnd(0x15025));
            public static readonly ShapeId S4_T32_I   = new(GuidHelper.FromIntAtEnd(0x115025));
            public static readonly ShapeId S4_2       = new(GuidHelper.FromIntAtEnd(0x15120));
            public static readonly ShapeId S4_2_I     = new(GuidHelper.FromIntAtEnd(0x115120));
            public static readonly ShapeId S4_2_T2    = new(GuidHelper.FromIntAtEnd(0x15121));
            public static readonly ShapeId S4_2_T2_I  = new(GuidHelper.FromIntAtEnd(0x115121));
            public static readonly ShapeId S4_2_T4    = new(GuidHelper.FromIntAtEnd(0x15122));
            public static readonly ShapeId S4_2_T4_I  = new(GuidHelper.FromIntAtEnd(0x115122));
            public static readonly ShapeId S4_2_T8    = new(GuidHelper.FromIntAtEnd(0x15123));
            public static readonly ShapeId S4_2_T8_I  = new(GuidHelper.FromIntAtEnd(0x115123));
            public static readonly ShapeId S4_2_T16   = new(GuidHelper.FromIntAtEnd(0x15124));
            public static readonly ShapeId S4_2_T16_I = new(GuidHelper.FromIntAtEnd(0x115124));
            public static readonly ShapeId S4_2_T32   = new(GuidHelper.FromIntAtEnd(0x15125));
            public static readonly ShapeId S4_2_T32_I = new(GuidHelper.FromIntAtEnd(0x115125));
        }

        /// <summary> Hexagon - 48 shapes. </summary>
        public static class Hexagon
        {
            public static readonly ShapeId Fill       = new(GuidHelper.FromIntAtEnd(0x16000));
            public static readonly ShapeId I          = new(GuidHelper.FromIntAtEnd(0x116000));
            public static readonly ShapeId T2         = new(GuidHelper.FromIntAtEnd(0x16001));
            public static readonly ShapeId T2_I       = new(GuidHelper.FromIntAtEnd(0x116001));
            public static readonly ShapeId T4         = new(GuidHelper.FromIntAtEnd(0x16002));
            public static readonly ShapeId T4_I       = new(GuidHelper.FromIntAtEnd(0x116002));
            public static readonly ShapeId T8         = new(GuidHelper.FromIntAtEnd(0x16003));
            public static readonly ShapeId T8_I       = new(GuidHelper.FromIntAtEnd(0x116003));
            public static readonly ShapeId T16        = new(GuidHelper.FromIntAtEnd(0x16004));
            public static readonly ShapeId T16_I      = new(GuidHelper.FromIntAtEnd(0x116004));
            public static readonly ShapeId T32        = new(GuidHelper.FromIntAtEnd(0x16005));
            public static readonly ShapeId T32_I      = new(GuidHelper.FromIntAtEnd(0x116005));
            public static readonly ShapeId S2         = new(GuidHelper.FromIntAtEnd(0x16010));
            public static readonly ShapeId S2_I       = new(GuidHelper.FromIntAtEnd(0x116010));
            public static readonly ShapeId S2_T2      = new(GuidHelper.FromIntAtEnd(0x16011));
            public static readonly ShapeId S2_T2_I    = new(GuidHelper.FromIntAtEnd(0x116011));
            public static readonly ShapeId S2_T4      = new(GuidHelper.FromIntAtEnd(0x16012));
            public static readonly ShapeId S2_T4_I    = new(GuidHelper.FromIntAtEnd(0x116012));
            public static readonly ShapeId S2_T8      = new(GuidHelper.FromIntAtEnd(0x16013));
            public static readonly ShapeId S2_T8_I    = new(GuidHelper.FromIntAtEnd(0x116013));
            public static readonly ShapeId S2_T16     = new(GuidHelper.FromIntAtEnd(0x16014));
            public static readonly ShapeId S2_T16_I   = new(GuidHelper.FromIntAtEnd(0x116014));
            public static readonly ShapeId S2_T32     = new(GuidHelper.FromIntAtEnd(0x16015));
            public static readonly ShapeId S2_T32_I   = new(GuidHelper.FromIntAtEnd(0x116015));
            public static readonly ShapeId S4         = new(GuidHelper.FromIntAtEnd(0x16020));
            public static readonly ShapeId S4_I       = new(GuidHelper.FromIntAtEnd(0x116020));
            public static readonly ShapeId S4_T2      = new(GuidHelper.FromIntAtEnd(0x16021));
            public static readonly ShapeId S4_T2_I    = new(GuidHelper.FromIntAtEnd(0x116021));
            public static readonly ShapeId S4_T4      = new(GuidHelper.FromIntAtEnd(0x16022));
            public static readonly ShapeId S4_T4_I    = new(GuidHelper.FromIntAtEnd(0x116022));
            public static readonly ShapeId S4_T8      = new(GuidHelper.FromIntAtEnd(0x16023));
            public static readonly ShapeId S4_T8_I    = new(GuidHelper.FromIntAtEnd(0x116023));
            public static readonly ShapeId S4_T16     = new(GuidHelper.FromIntAtEnd(0x16024));
            public static readonly ShapeId S4_T16_I   = new(GuidHelper.FromIntAtEnd(0x116024));
            public static readonly ShapeId S4_T32     = new(GuidHelper.FromIntAtEnd(0x16025));
            public static readonly ShapeId S4_T32_I   = new(GuidHelper.FromIntAtEnd(0x116025));
            public static readonly ShapeId S4_2       = new(GuidHelper.FromIntAtEnd(0x16120));
            public static readonly ShapeId S4_2_I     = new(GuidHelper.FromIntAtEnd(0x116120));
            public static readonly ShapeId S4_2_T2    = new(GuidHelper.FromIntAtEnd(0x16121));
            public static readonly ShapeId S4_2_T2_I  = new(GuidHelper.FromIntAtEnd(0x116121));
            public static readonly ShapeId S4_2_T4    = new(GuidHelper.FromIntAtEnd(0x16122));
            public static readonly ShapeId S4_2_T4_I  = new(GuidHelper.FromIntAtEnd(0x116122));
            public static readonly ShapeId S4_2_T8    = new(GuidHelper.FromIntAtEnd(0x16123));
            public static readonly ShapeId S4_2_T8_I  = new(GuidHelper.FromIntAtEnd(0x116123));
            public static readonly ShapeId S4_2_T16   = new(GuidHelper.FromIntAtEnd(0x16124));
            public static readonly ShapeId S4_2_T16_I = new(GuidHelper.FromIntAtEnd(0x116124));
            public static readonly ShapeId S4_2_T32   = new(GuidHelper.FromIntAtEnd(0x16125));
            public static readonly ShapeId S4_2_T32_I = new(GuidHelper.FromIntAtEnd(0x116125));
        }

        /// <summary> Heptagon - 48 shapes. </summary>
        public static class Heptagon
        {
            public static readonly ShapeId Fill       = new(GuidHelper.FromIntAtEnd(0x17000));
            public static readonly ShapeId I          = new(GuidHelper.FromIntAtEnd(0x117000));
            public static readonly ShapeId T2         = new(GuidHelper.FromIntAtEnd(0x17001));
            public static readonly ShapeId T2_I       = new(GuidHelper.FromIntAtEnd(0x117001));
            public static readonly ShapeId T4         = new(GuidHelper.FromIntAtEnd(0x17002));
            public static readonly ShapeId T4_I       = new(GuidHelper.FromIntAtEnd(0x117002));
            public static readonly ShapeId T8         = new(GuidHelper.FromIntAtEnd(0x17003));
            public static readonly ShapeId T8_I       = new(GuidHelper.FromIntAtEnd(0x117003));
            public static readonly ShapeId T16        = new(GuidHelper.FromIntAtEnd(0x17004));
            public static readonly ShapeId T16_I      = new(GuidHelper.FromIntAtEnd(0x117004));
            public static readonly ShapeId T32        = new(GuidHelper.FromIntAtEnd(0x17005));
            public static readonly ShapeId T32_I      = new(GuidHelper.FromIntAtEnd(0x117005));
            public static readonly ShapeId S2         = new(GuidHelper.FromIntAtEnd(0x17010));
            public static readonly ShapeId S2_I       = new(GuidHelper.FromIntAtEnd(0x117010));
            public static readonly ShapeId S2_T2      = new(GuidHelper.FromIntAtEnd(0x17011));
            public static readonly ShapeId S2_T2_I    = new(GuidHelper.FromIntAtEnd(0x117011));
            public static readonly ShapeId S2_T4      = new(GuidHelper.FromIntAtEnd(0x17012));
            public static readonly ShapeId S2_T4_I    = new(GuidHelper.FromIntAtEnd(0x117012));
            public static readonly ShapeId S2_T8      = new(GuidHelper.FromIntAtEnd(0x17013));
            public static readonly ShapeId S2_T8_I    = new(GuidHelper.FromIntAtEnd(0x117013));
            public static readonly ShapeId S2_T16     = new(GuidHelper.FromIntAtEnd(0x17014));
            public static readonly ShapeId S2_T16_I   = new(GuidHelper.FromIntAtEnd(0x117014));
            public static readonly ShapeId S2_T32     = new(GuidHelper.FromIntAtEnd(0x17015));
            public static readonly ShapeId S2_T32_I   = new(GuidHelper.FromIntAtEnd(0x117015));
            public static readonly ShapeId S4         = new(GuidHelper.FromIntAtEnd(0x17020));
            public static readonly ShapeId S4_I       = new(GuidHelper.FromIntAtEnd(0x117020));
            public static readonly ShapeId S4_T2      = new(GuidHelper.FromIntAtEnd(0x17021));
            public static readonly ShapeId S4_T2_I    = new(GuidHelper.FromIntAtEnd(0x117021));
            public static readonly ShapeId S4_T4      = new(GuidHelper.FromIntAtEnd(0x17022));
            public static readonly ShapeId S4_T4_I    = new(GuidHelper.FromIntAtEnd(0x117022));
            public static readonly ShapeId S4_T8      = new(GuidHelper.FromIntAtEnd(0x17023));
            public static readonly ShapeId S4_T8_I    = new(GuidHelper.FromIntAtEnd(0x117023));
            public static readonly ShapeId S4_T16     = new(GuidHelper.FromIntAtEnd(0x17024));
            public static readonly ShapeId S4_T16_I   = new(GuidHelper.FromIntAtEnd(0x117024));
            public static readonly ShapeId S4_T32     = new(GuidHelper.FromIntAtEnd(0x17025));
            public static readonly ShapeId S4_T32_I   = new(GuidHelper.FromIntAtEnd(0x117025));
            public static readonly ShapeId S4_2       = new(GuidHelper.FromIntAtEnd(0x17120));
            public static readonly ShapeId S4_2_I     = new(GuidHelper.FromIntAtEnd(0x117120));
            public static readonly ShapeId S4_2_T2    = new(GuidHelper.FromIntAtEnd(0x17121));
            public static readonly ShapeId S4_2_T2_I  = new(GuidHelper.FromIntAtEnd(0x117121));
            public static readonly ShapeId S4_2_T4    = new(GuidHelper.FromIntAtEnd(0x17122));
            public static readonly ShapeId S4_2_T4_I  = new(GuidHelper.FromIntAtEnd(0x117122));
            public static readonly ShapeId S4_2_T8    = new(GuidHelper.FromIntAtEnd(0x17123));
            public static readonly ShapeId S4_2_T8_I  = new(GuidHelper.FromIntAtEnd(0x117123));
            public static readonly ShapeId S4_2_T16   = new(GuidHelper.FromIntAtEnd(0x17124));
            public static readonly ShapeId S4_2_T16_I = new(GuidHelper.FromIntAtEnd(0x117124));
            public static readonly ShapeId S4_2_T32   = new(GuidHelper.FromIntAtEnd(0x17125));
            public static readonly ShapeId S4_2_T32_I = new(GuidHelper.FromIntAtEnd(0x117125));
        }

        /// <summary> Octagon - 48 shapes. </summary>
        public static class Octagon
        {
            public static readonly ShapeId Fill     = new(GuidHelper.FromIntAtEnd(0x18000));
            public static readonly ShapeId I        = new(GuidHelper.FromIntAtEnd(0x118000));
            public static readonly ShapeId T2       = new(GuidHelper.FromIntAtEnd(0x18001));
            public static readonly ShapeId T2_I     = new(GuidHelper.FromIntAtEnd(0x118001));
            public static readonly ShapeId T4       = new(GuidHelper.FromIntAtEnd(0x18002));
            public static readonly ShapeId T4_I     = new(GuidHelper.FromIntAtEnd(0x118002));
            public static readonly ShapeId T8       = new(GuidHelper.FromIntAtEnd(0x18003));
            public static readonly ShapeId T8_I     = new(GuidHelper.FromIntAtEnd(0x118003));
            public static readonly ShapeId T16      = new(GuidHelper.FromIntAtEnd(0x18004));
            public static readonly ShapeId T16_I    = new(GuidHelper.FromIntAtEnd(0x118004));
            public static readonly ShapeId T32      = new(GuidHelper.FromIntAtEnd(0x18005));
            public static readonly ShapeId T32_I    = new(GuidHelper.FromIntAtEnd(0x118005));
            public static readonly ShapeId S2       = new(GuidHelper.FromIntAtEnd(0x18010));
            public static readonly ShapeId S2_I     = new(GuidHelper.FromIntAtEnd(0x118010));
            public static readonly ShapeId S2_T2    = new(GuidHelper.FromIntAtEnd(0x18011));
            public static readonly ShapeId S2_T2_I  = new(GuidHelper.FromIntAtEnd(0x118011));
            public static readonly ShapeId S2_T4    = new(GuidHelper.FromIntAtEnd(0x18012));
            public static readonly ShapeId S2_T4_I  = new(GuidHelper.FromIntAtEnd(0x118012));
            public static readonly ShapeId S2_T8    = new(GuidHelper.FromIntAtEnd(0x18013));
            public static readonly ShapeId S2_T8_I  = new(GuidHelper.FromIntAtEnd(0x118013));
            public static readonly ShapeId S2_T16   = new(GuidHelper.FromIntAtEnd(0x18014));
            public static readonly ShapeId S2_T16_I = new(GuidHelper.FromIntAtEnd(0x118014));
            public static readonly ShapeId S2_T32   = new(GuidHelper.FromIntAtEnd(0x18015));
            public static readonly ShapeId S2_T32_I = new(GuidHelper.FromIntAtEnd(0x118015));
            public static readonly ShapeId S4       = new(GuidHelper.FromIntAtEnd(0x18020));
            public static readonly ShapeId S4_I     = new(GuidHelper.FromIntAtEnd(0x118020));
            public static readonly ShapeId S4_T2    = new(GuidHelper.FromIntAtEnd(0x18021));
            public static readonly ShapeId S4_T2_I  = new(GuidHelper.FromIntAtEnd(0x118021));
            public static readonly ShapeId S4_T4    = new(GuidHelper.FromIntAtEnd(0x18022));
            public static readonly ShapeId S4_T4_I  = new(GuidHelper.FromIntAtEnd(0x118022));
            public static readonly ShapeId S4_T8    = new(GuidHelper.FromIntAtEnd(0x18023));
            public static readonly ShapeId S4_T8_I  = new(GuidHelper.FromIntAtEnd(0x118023));
            public static readonly ShapeId S4_T16   = new(GuidHelper.FromIntAtEnd(0x18024));
            public static readonly ShapeId S4_T16_I = new(GuidHelper.FromIntAtEnd(0x118024));
            public static readonly ShapeId S4_T32   = new(GuidHelper.FromIntAtEnd(0x18025));
            public static readonly ShapeId S4_T32_I = new(GuidHelper.FromIntAtEnd(0x118025));
            public static readonly ShapeId S8       = new(GuidHelper.FromIntAtEnd(0x18030));
            public static readonly ShapeId S8_I     = new(GuidHelper.FromIntAtEnd(0x118030));
            public static readonly ShapeId S8_T2    = new(GuidHelper.FromIntAtEnd(0x18031));
            public static readonly ShapeId S8_T2_I  = new(GuidHelper.FromIntAtEnd(0x118031));
            public static readonly ShapeId S8_T4    = new(GuidHelper.FromIntAtEnd(0x18032));
            public static readonly ShapeId S8_T4_I  = new(GuidHelper.FromIntAtEnd(0x118032));
            public static readonly ShapeId S8_T8    = new(GuidHelper.FromIntAtEnd(0x18033));
            public static readonly ShapeId S8_T8_I  = new(GuidHelper.FromIntAtEnd(0x118033));
            public static readonly ShapeId S8_T16   = new(GuidHelper.FromIntAtEnd(0x18034));
            public static readonly ShapeId S8_T16_I = new(GuidHelper.FromIntAtEnd(0x118034));
            public static readonly ShapeId S8_T32   = new(GuidHelper.FromIntAtEnd(0x18035));
            public static readonly ShapeId S8_T32_I = new(GuidHelper.FromIntAtEnd(0x118035));
        }

        /// <summary> Nonagon - 48 shapes. </summary>
        public static class Nonagon
        {
            public static readonly ShapeId Fill       = new(GuidHelper.FromIntAtEnd(0x19000));
            public static readonly ShapeId I          = new(GuidHelper.FromIntAtEnd(0x119000));
            public static readonly ShapeId T2         = new(GuidHelper.FromIntAtEnd(0x19001));
            public static readonly ShapeId T2_I       = new(GuidHelper.FromIntAtEnd(0x119001));
            public static readonly ShapeId T4         = new(GuidHelper.FromIntAtEnd(0x19002));
            public static readonly ShapeId T4_I       = new(GuidHelper.FromIntAtEnd(0x119002));
            public static readonly ShapeId T8         = new(GuidHelper.FromIntAtEnd(0x19003));
            public static readonly ShapeId T8_I       = new(GuidHelper.FromIntAtEnd(0x119003));
            public static readonly ShapeId T16        = new(GuidHelper.FromIntAtEnd(0x19004));
            public static readonly ShapeId T16_I      = new(GuidHelper.FromIntAtEnd(0x119004));
            public static readonly ShapeId T32        = new(GuidHelper.FromIntAtEnd(0x19005));
            public static readonly ShapeId T32_I      = new(GuidHelper.FromIntAtEnd(0x119005));
            public static readonly ShapeId S2         = new(GuidHelper.FromIntAtEnd(0x19010));
            public static readonly ShapeId S2_I       = new(GuidHelper.FromIntAtEnd(0x119010));
            public static readonly ShapeId S2_T2      = new(GuidHelper.FromIntAtEnd(0x19011));
            public static readonly ShapeId S2_T2_I    = new(GuidHelper.FromIntAtEnd(0x119011));
            public static readonly ShapeId S2_T4      = new(GuidHelper.FromIntAtEnd(0x19012));
            public static readonly ShapeId S2_T4_I    = new(GuidHelper.FromIntAtEnd(0x119012));
            public static readonly ShapeId S2_T8      = new(GuidHelper.FromIntAtEnd(0x19013));
            public static readonly ShapeId S2_T8_I    = new(GuidHelper.FromIntAtEnd(0x119013));
            public static readonly ShapeId S2_T16     = new(GuidHelper.FromIntAtEnd(0x19014));
            public static readonly ShapeId S2_T16_I   = new(GuidHelper.FromIntAtEnd(0x119014));
            public static readonly ShapeId S2_T32     = new(GuidHelper.FromIntAtEnd(0x19015));
            public static readonly ShapeId S2_T32_I   = new(GuidHelper.FromIntAtEnd(0x119015));
            public static readonly ShapeId S4         = new(GuidHelper.FromIntAtEnd(0x19020));
            public static readonly ShapeId S4_I       = new(GuidHelper.FromIntAtEnd(0x119020));
            public static readonly ShapeId S4_T2      = new(GuidHelper.FromIntAtEnd(0x19021));
            public static readonly ShapeId S4_T2_I    = new(GuidHelper.FromIntAtEnd(0x119021));
            public static readonly ShapeId S4_T4      = new(GuidHelper.FromIntAtEnd(0x19022));
            public static readonly ShapeId S4_T4_I    = new(GuidHelper.FromIntAtEnd(0x119022));
            public static readonly ShapeId S4_T8      = new(GuidHelper.FromIntAtEnd(0x19023));
            public static readonly ShapeId S4_T8_I    = new(GuidHelper.FromIntAtEnd(0x119023));
            public static readonly ShapeId S4_T16     = new(GuidHelper.FromIntAtEnd(0x19024));
            public static readonly ShapeId S4_T16_I   = new(GuidHelper.FromIntAtEnd(0x119024));
            public static readonly ShapeId S4_T32     = new(GuidHelper.FromIntAtEnd(0x19025));
            public static readonly ShapeId S4_T32_I   = new(GuidHelper.FromIntAtEnd(0x119025));
            public static readonly ShapeId S4_2       = new(GuidHelper.FromIntAtEnd(0x19120));
            public static readonly ShapeId S4_2_I     = new(GuidHelper.FromIntAtEnd(0x119120));
            public static readonly ShapeId S4_2_T2    = new(GuidHelper.FromIntAtEnd(0x19121));
            public static readonly ShapeId S4_2_T2_I  = new(GuidHelper.FromIntAtEnd(0x119121));
            public static readonly ShapeId S4_2_T4    = new(GuidHelper.FromIntAtEnd(0x19122));
            public static readonly ShapeId S4_2_T4_I  = new(GuidHelper.FromIntAtEnd(0x119122));
            public static readonly ShapeId S4_2_T8    = new(GuidHelper.FromIntAtEnd(0x19123));
            public static readonly ShapeId S4_2_T8_I  = new(GuidHelper.FromIntAtEnd(0x119123));
            public static readonly ShapeId S4_2_T16   = new(GuidHelper.FromIntAtEnd(0x19124));
            public static readonly ShapeId S4_2_T16_I = new(GuidHelper.FromIntAtEnd(0x119124));
            public static readonly ShapeId S4_2_T32   = new(GuidHelper.FromIntAtEnd(0x19125));
            public static readonly ShapeId S4_2_T32_I = new(GuidHelper.FromIntAtEnd(0x119125));
        }

        /// <summary> Decagon - 48 shapes. </summary>
        public static class Decagon
        {
            public static readonly ShapeId Fill       = new(GuidHelper.FromIntAtEnd(0x1A000));
            public static readonly ShapeId I          = new(GuidHelper.FromIntAtEnd(0x11A000));
            public static readonly ShapeId T2         = new(GuidHelper.FromIntAtEnd(0x1A001));
            public static readonly ShapeId T2_I       = new(GuidHelper.FromIntAtEnd(0x11A001));
            public static readonly ShapeId T4         = new(GuidHelper.FromIntAtEnd(0x1A002));
            public static readonly ShapeId T4_I       = new(GuidHelper.FromIntAtEnd(0x11A002));
            public static readonly ShapeId T8         = new(GuidHelper.FromIntAtEnd(0x1A003));
            public static readonly ShapeId T8_I       = new(GuidHelper.FromIntAtEnd(0x11A003));
            public static readonly ShapeId T16        = new(GuidHelper.FromIntAtEnd(0x1A004));
            public static readonly ShapeId T16_I      = new(GuidHelper.FromIntAtEnd(0x11A004));
            public static readonly ShapeId T32        = new(GuidHelper.FromIntAtEnd(0x1A005));
            public static readonly ShapeId T32_I      = new(GuidHelper.FromIntAtEnd(0x11A005));
            public static readonly ShapeId S2         = new(GuidHelper.FromIntAtEnd(0x1A010));
            public static readonly ShapeId S2_I       = new(GuidHelper.FromIntAtEnd(0x11A010));
            public static readonly ShapeId S2_T2      = new(GuidHelper.FromIntAtEnd(0x1A011));
            public static readonly ShapeId S2_T2_I    = new(GuidHelper.FromIntAtEnd(0x11A011));
            public static readonly ShapeId S2_T4      = new(GuidHelper.FromIntAtEnd(0x1A012));
            public static readonly ShapeId S2_T4_I    = new(GuidHelper.FromIntAtEnd(0x11A012));
            public static readonly ShapeId S2_T8      = new(GuidHelper.FromIntAtEnd(0x1A013));
            public static readonly ShapeId S2_T8_I    = new(GuidHelper.FromIntAtEnd(0x11A013));
            public static readonly ShapeId S2_T16     = new(GuidHelper.FromIntAtEnd(0x1A014));
            public static readonly ShapeId S2_T16_I   = new(GuidHelper.FromIntAtEnd(0x11A014));
            public static readonly ShapeId S2_T32     = new(GuidHelper.FromIntAtEnd(0x1A015));
            public static readonly ShapeId S2_T32_I   = new(GuidHelper.FromIntAtEnd(0x11A015));
            public static readonly ShapeId S4         = new(GuidHelper.FromIntAtEnd(0x1A020));
            public static readonly ShapeId S4_I       = new(GuidHelper.FromIntAtEnd(0x11A020));
            public static readonly ShapeId S4_T2      = new(GuidHelper.FromIntAtEnd(0x1A021));
            public static readonly ShapeId S4_T2_I    = new(GuidHelper.FromIntAtEnd(0x11A021));
            public static readonly ShapeId S4_T4      = new(GuidHelper.FromIntAtEnd(0x1A022));
            public static readonly ShapeId S4_T4_I    = new(GuidHelper.FromIntAtEnd(0x11A022));
            public static readonly ShapeId S4_T8      = new(GuidHelper.FromIntAtEnd(0x1A023));
            public static readonly ShapeId S4_T8_I    = new(GuidHelper.FromIntAtEnd(0x11A023));
            public static readonly ShapeId S4_T16     = new(GuidHelper.FromIntAtEnd(0x1A024));
            public static readonly ShapeId S4_T16_I   = new(GuidHelper.FromIntAtEnd(0x11A024));
            public static readonly ShapeId S4_T32     = new(GuidHelper.FromIntAtEnd(0x1A025));
            public static readonly ShapeId S4_T32_I   = new(GuidHelper.FromIntAtEnd(0x11A025));
            public static readonly ShapeId S4_2       = new(GuidHelper.FromIntAtEnd(0x1A120));
            public static readonly ShapeId S4_2_I     = new(GuidHelper.FromIntAtEnd(0x11A120));
            public static readonly ShapeId S4_2_T2    = new(GuidHelper.FromIntAtEnd(0x1A121));
            public static readonly ShapeId S4_2_T2_I  = new(GuidHelper.FromIntAtEnd(0x11A121));
            public static readonly ShapeId S4_2_T4    = new(GuidHelper.FromIntAtEnd(0x1A122));
            public static readonly ShapeId S4_2_T4_I  = new(GuidHelper.FromIntAtEnd(0x11A122));
            public static readonly ShapeId S4_2_T8    = new(GuidHelper.FromIntAtEnd(0x1A123));
            public static readonly ShapeId S4_2_T8_I  = new(GuidHelper.FromIntAtEnd(0x11A123));
            public static readonly ShapeId S4_2_T16   = new(GuidHelper.FromIntAtEnd(0x1A124));
            public static readonly ShapeId S4_2_T16_I = new(GuidHelper.FromIntAtEnd(0x11A124));
            public static readonly ShapeId S4_2_T32   = new(GuidHelper.FromIntAtEnd(0x1A125));
            public static readonly ShapeId S4_2_T32_I = new(GuidHelper.FromIntAtEnd(0x11A125));
        }

        /// <summary> Hendecagon - 48 shapes. </summary>
        public static class Hendecagon
        {
            public static readonly ShapeId Fill       = new(GuidHelper.FromIntAtEnd(0x1B000));
            public static readonly ShapeId I          = new(GuidHelper.FromIntAtEnd(0x11B000));
            public static readonly ShapeId T2         = new(GuidHelper.FromIntAtEnd(0x1B001));
            public static readonly ShapeId T2_I       = new(GuidHelper.FromIntAtEnd(0x11B001));
            public static readonly ShapeId T4         = new(GuidHelper.FromIntAtEnd(0x1B002));
            public static readonly ShapeId T4_I       = new(GuidHelper.FromIntAtEnd(0x11B002));
            public static readonly ShapeId T8         = new(GuidHelper.FromIntAtEnd(0x1B003));
            public static readonly ShapeId T8_I       = new(GuidHelper.FromIntAtEnd(0x11B003));
            public static readonly ShapeId T16        = new(GuidHelper.FromIntAtEnd(0x1B004));
            public static readonly ShapeId T16_I      = new(GuidHelper.FromIntAtEnd(0x11B004));
            public static readonly ShapeId T32        = new(GuidHelper.FromIntAtEnd(0x1B005));
            public static readonly ShapeId T32_I      = new(GuidHelper.FromIntAtEnd(0x11B005));
            public static readonly ShapeId S2         = new(GuidHelper.FromIntAtEnd(0x1B010));
            public static readonly ShapeId S2_I       = new(GuidHelper.FromIntAtEnd(0x11B010));
            public static readonly ShapeId S2_T2      = new(GuidHelper.FromIntAtEnd(0x1B011));
            public static readonly ShapeId S2_T2_I    = new(GuidHelper.FromIntAtEnd(0x11B011));
            public static readonly ShapeId S2_T4      = new(GuidHelper.FromIntAtEnd(0x1B012));
            public static readonly ShapeId S2_T4_I    = new(GuidHelper.FromIntAtEnd(0x11B012));
            public static readonly ShapeId S2_T8      = new(GuidHelper.FromIntAtEnd(0x1B013));
            public static readonly ShapeId S2_T8_I    = new(GuidHelper.FromIntAtEnd(0x11B013));
            public static readonly ShapeId S2_T16     = new(GuidHelper.FromIntAtEnd(0x1B014));
            public static readonly ShapeId S2_T16_I   = new(GuidHelper.FromIntAtEnd(0x11B014));
            public static readonly ShapeId S2_T32     = new(GuidHelper.FromIntAtEnd(0x1B015));
            public static readonly ShapeId S2_T32_I   = new(GuidHelper.FromIntAtEnd(0x11B015));
            public static readonly ShapeId S4         = new(GuidHelper.FromIntAtEnd(0x1B020));
            public static readonly ShapeId S4_I       = new(GuidHelper.FromIntAtEnd(0x11B020));
            public static readonly ShapeId S4_T2      = new(GuidHelper.FromIntAtEnd(0x1B021));
            public static readonly ShapeId S4_T2_I    = new(GuidHelper.FromIntAtEnd(0x11B021));
            public static readonly ShapeId S4_T4      = new(GuidHelper.FromIntAtEnd(0x1B022));
            public static readonly ShapeId S4_T4_I    = new(GuidHelper.FromIntAtEnd(0x11B022));
            public static readonly ShapeId S4_T8      = new(GuidHelper.FromIntAtEnd(0x1B023));
            public static readonly ShapeId S4_T8_I    = new(GuidHelper.FromIntAtEnd(0x11B023));
            public static readonly ShapeId S4_T16     = new(GuidHelper.FromIntAtEnd(0x1B024));
            public static readonly ShapeId S4_T16_I   = new(GuidHelper.FromIntAtEnd(0x11B024));
            public static readonly ShapeId S4_T32     = new(GuidHelper.FromIntAtEnd(0x1B025));
            public static readonly ShapeId S4_T32_I   = new(GuidHelper.FromIntAtEnd(0x11B025));
            public static readonly ShapeId S4_2       = new(GuidHelper.FromIntAtEnd(0x1B120));
            public static readonly ShapeId S4_2_I     = new(GuidHelper.FromIntAtEnd(0x11B120));
            public static readonly ShapeId S4_2_T2    = new(GuidHelper.FromIntAtEnd(0x1B121));
            public static readonly ShapeId S4_2_T2_I  = new(GuidHelper.FromIntAtEnd(0x11B121));
            public static readonly ShapeId S4_2_T4    = new(GuidHelper.FromIntAtEnd(0x1B122));
            public static readonly ShapeId S4_2_T4_I  = new(GuidHelper.FromIntAtEnd(0x11B122));
            public static readonly ShapeId S4_2_T8    = new(GuidHelper.FromIntAtEnd(0x1B123));
            public static readonly ShapeId S4_2_T8_I  = new(GuidHelper.FromIntAtEnd(0x11B123));
            public static readonly ShapeId S4_2_T16   = new(GuidHelper.FromIntAtEnd(0x1B124));
            public static readonly ShapeId S4_2_T16_I = new(GuidHelper.FromIntAtEnd(0x11B124));
            public static readonly ShapeId S4_2_T32   = new(GuidHelper.FromIntAtEnd(0x1B125));
            public static readonly ShapeId S4_2_T32_I = new(GuidHelper.FromIntAtEnd(0x11B125));
        }

        /// <summary> Dodecagon - 36 shapes. </summary>
        public static class Dodecagon
        {
            public static readonly ShapeId Fill     = new(GuidHelper.FromIntAtEnd(0x1C000));
            public static readonly ShapeId I        = new(GuidHelper.FromIntAtEnd(0x11C000));
            public static readonly ShapeId T2       = new(GuidHelper.FromIntAtEnd(0x1C001));
            public static readonly ShapeId T2_I     = new(GuidHelper.FromIntAtEnd(0x11C001));
            public static readonly ShapeId T4       = new(GuidHelper.FromIntAtEnd(0x1C002));
            public static readonly ShapeId T4_I     = new(GuidHelper.FromIntAtEnd(0x11C002));
            public static readonly ShapeId T8       = new(GuidHelper.FromIntAtEnd(0x1C003));
            public static readonly ShapeId T8_I     = new(GuidHelper.FromIntAtEnd(0x11C003));
            public static readonly ShapeId T16      = new(GuidHelper.FromIntAtEnd(0x1C004));
            public static readonly ShapeId T16_I    = new(GuidHelper.FromIntAtEnd(0x11C004));
            public static readonly ShapeId T32      = new(GuidHelper.FromIntAtEnd(0x1C005));
            public static readonly ShapeId T32_I    = new(GuidHelper.FromIntAtEnd(0x11C005));
            public static readonly ShapeId S2       = new(GuidHelper.FromIntAtEnd(0x1C010));
            public static readonly ShapeId S2_I     = new(GuidHelper.FromIntAtEnd(0x11C010));
            public static readonly ShapeId S2_T2    = new(GuidHelper.FromIntAtEnd(0x1C011));
            public static readonly ShapeId S2_T2_I  = new(GuidHelper.FromIntAtEnd(0x11C011));
            public static readonly ShapeId S2_T4    = new(GuidHelper.FromIntAtEnd(0x1C012));
            public static readonly ShapeId S2_T4_I  = new(GuidHelper.FromIntAtEnd(0x11C012));
            public static readonly ShapeId S2_T8    = new(GuidHelper.FromIntAtEnd(0x1C013));
            public static readonly ShapeId S2_T8_I  = new(GuidHelper.FromIntAtEnd(0x11C013));
            public static readonly ShapeId S2_T16   = new(GuidHelper.FromIntAtEnd(0x1C014));
            public static readonly ShapeId S2_T16_I = new(GuidHelper.FromIntAtEnd(0x11C014));
            public static readonly ShapeId S2_T32   = new(GuidHelper.FromIntAtEnd(0x1C015));
            public static readonly ShapeId S2_T32_I = new(GuidHelper.FromIntAtEnd(0x11C015));
            public static readonly ShapeId S4       = new(GuidHelper.FromIntAtEnd(0x1C020));
            public static readonly ShapeId S4_I     = new(GuidHelper.FromIntAtEnd(0x11C020));
            public static readonly ShapeId S4_T2    = new(GuidHelper.FromIntAtEnd(0x1C021));
            public static readonly ShapeId S4_T2_I  = new(GuidHelper.FromIntAtEnd(0x11C021));
            public static readonly ShapeId S4_T4    = new(GuidHelper.FromIntAtEnd(0x1C022));
            public static readonly ShapeId S4_T4_I  = new(GuidHelper.FromIntAtEnd(0x11C022));
            public static readonly ShapeId S4_T8    = new(GuidHelper.FromIntAtEnd(0x1C023));
            public static readonly ShapeId S4_T8_I  = new(GuidHelper.FromIntAtEnd(0x11C023));
            public static readonly ShapeId S4_T16   = new(GuidHelper.FromIntAtEnd(0x1C024));
            public static readonly ShapeId S4_T16_I = new(GuidHelper.FromIntAtEnd(0x11C024));
            public static readonly ShapeId S4_T32   = new(GuidHelper.FromIntAtEnd(0x1C025));
            public static readonly ShapeId S4_T32_I = new(GuidHelper.FromIntAtEnd(0x11C025));
        }

        /// <summary> Hexadecagon - 48 shapes. </summary>
        public static class Hexadecagon
        {
            public static readonly ShapeId Fill     = new(GuidHelper.FromIntAtEnd(0x20000));
            public static readonly ShapeId I        = new(GuidHelper.FromIntAtEnd(0x120000));
            public static readonly ShapeId T2       = new(GuidHelper.FromIntAtEnd(0x20001));
            public static readonly ShapeId T2_I     = new(GuidHelper.FromIntAtEnd(0x120001));
            public static readonly ShapeId T4       = new(GuidHelper.FromIntAtEnd(0x20002));
            public static readonly ShapeId T4_I     = new(GuidHelper.FromIntAtEnd(0x120002));
            public static readonly ShapeId T8       = new(GuidHelper.FromIntAtEnd(0x20003));
            public static readonly ShapeId T8_I     = new(GuidHelper.FromIntAtEnd(0x120003));
            public static readonly ShapeId T16      = new(GuidHelper.FromIntAtEnd(0x20004));
            public static readonly ShapeId T16_I    = new(GuidHelper.FromIntAtEnd(0x120004));
            public static readonly ShapeId T32      = new(GuidHelper.FromIntAtEnd(0x20005));
            public static readonly ShapeId T32_I    = new(GuidHelper.FromIntAtEnd(0x120005));
            public static readonly ShapeId S2       = new(GuidHelper.FromIntAtEnd(0x20010));
            public static readonly ShapeId S2_I     = new(GuidHelper.FromIntAtEnd(0x120010));
            public static readonly ShapeId S2_T2    = new(GuidHelper.FromIntAtEnd(0x20011));
            public static readonly ShapeId S2_T2_I  = new(GuidHelper.FromIntAtEnd(0x120011));
            public static readonly ShapeId S2_T4    = new(GuidHelper.FromIntAtEnd(0x20012));
            public static readonly ShapeId S2_T4_I  = new(GuidHelper.FromIntAtEnd(0x120012));
            public static readonly ShapeId S2_T8    = new(GuidHelper.FromIntAtEnd(0x20013));
            public static readonly ShapeId S2_T8_I  = new(GuidHelper.FromIntAtEnd(0x120013));
            public static readonly ShapeId S2_T16   = new(GuidHelper.FromIntAtEnd(0x20014));
            public static readonly ShapeId S2_T16_I = new(GuidHelper.FromIntAtEnd(0x120014));
            public static readonly ShapeId S2_T32   = new(GuidHelper.FromIntAtEnd(0x20015));
            public static readonly ShapeId S2_T32_I = new(GuidHelper.FromIntAtEnd(0x120015));
            public static readonly ShapeId S4       = new(GuidHelper.FromIntAtEnd(0x20020));
            public static readonly ShapeId S4_I     = new(GuidHelper.FromIntAtEnd(0x120020));
            public static readonly ShapeId S4_T2    = new(GuidHelper.FromIntAtEnd(0x20021));
            public static readonly ShapeId S4_T2_I  = new(GuidHelper.FromIntAtEnd(0x120021));
            public static readonly ShapeId S4_T4    = new(GuidHelper.FromIntAtEnd(0x20022));
            public static readonly ShapeId S4_T4_I  = new(GuidHelper.FromIntAtEnd(0x120022));
            public static readonly ShapeId S4_T8    = new(GuidHelper.FromIntAtEnd(0x20023));
            public static readonly ShapeId S4_T8_I  = new(GuidHelper.FromIntAtEnd(0x120023));
            public static readonly ShapeId S4_T16   = new(GuidHelper.FromIntAtEnd(0x20024));
            public static readonly ShapeId S4_T16_I = new(GuidHelper.FromIntAtEnd(0x120024));
            public static readonly ShapeId S4_T32   = new(GuidHelper.FromIntAtEnd(0x20025));
            public static readonly ShapeId S4_T32_I = new(GuidHelper.FromIntAtEnd(0x120025));
            public static readonly ShapeId S8       = new(GuidHelper.FromIntAtEnd(0x20030));
            public static readonly ShapeId S8_I     = new(GuidHelper.FromIntAtEnd(0x120030));
            public static readonly ShapeId S8_T2    = new(GuidHelper.FromIntAtEnd(0x20031));
            public static readonly ShapeId S8_T2_I  = new(GuidHelper.FromIntAtEnd(0x120031));
            public static readonly ShapeId S8_T4    = new(GuidHelper.FromIntAtEnd(0x20032));
            public static readonly ShapeId S8_T4_I  = new(GuidHelper.FromIntAtEnd(0x120032));
            public static readonly ShapeId S8_T8    = new(GuidHelper.FromIntAtEnd(0x20033));
            public static readonly ShapeId S8_T8_I  = new(GuidHelper.FromIntAtEnd(0x120033));
            public static readonly ShapeId S8_T16   = new(GuidHelper.FromIntAtEnd(0x20034));
            public static readonly ShapeId S8_T16_I = new(GuidHelper.FromIntAtEnd(0x120034));
            public static readonly ShapeId S8_T32   = new(GuidHelper.FromIntAtEnd(0x20035));
            public static readonly ShapeId S8_T32_I = new(GuidHelper.FromIntAtEnd(0x120035));
        }
    }
}
