using System;
using BH.SDK.Models.Interfaces;
using BH.SDK.Rules;
using BH.SDK.Rules.Attributes;
using Newtonsoft.Json;

// ReSharper disable NonReadonlyMemberInGetHashCode

namespace BH.SDK.Models.Hints
{
    /// <summary>
    /// How many objects of each kind the level needs alive at the same time, at its heaviest frame.
    /// Written by the editor on save (see LevelCapacityUtils.GetPeakUsage) so a player's game can
    /// preallocate its per-frame buffers before playback instead of growing them mid-level.
    /// <br/><br/>
    /// Strictly <b>advisory</b>: it comes from a file that may be hand-edited, generated by a third
    /// party tool, or simply stale. A consumer must treat it as a lower bound at most, recompute or
    /// grow on demand anyway, and clamp it against whatever the device actually allows. All zeroes
    /// (the default) means "no hint", not "no objects".
    /// </summary>
    [RuleContainer]
    public class LimitHints : IModel<LimitHints>
    {
        /// <summary> Peak count of objects of every type at once - the widest of them all. </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.Instances)]
        public int Instances { get; set; }

        // Shapes are counted in two buckets because a consumer draws them through two separate
        // pools - an opaque one that writes depth and a transparent one that blends - and neither
        // can borrow capacity from the other. Their sum is therefore normally larger than a single
        // "shapes" number would have been, and that is correct rather than double counting.
        //
        // ShaderType.Auto belongs to whichever bucket the CONSUMER resolves it into, and resolving
        // needs texture opacity, which lives outside this library. GetPeakUsage takes an optional
        // resolver for exactly that; with none, Auto counts as transparent - the same fallback the
        // consumer uses, and the safe direction to be wrong in, since an object wrongly sized into
        // the transparent pool still renders, just without depth rejection.

        /// <summary> Peak simultaneous shape objects on the opaque path - a subset of Instances. </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.ShapesOpaque)]
        public int ShapesOpaque { get; set; }

        /// <summary> Peak simultaneous shape objects on the transparent path - a subset of Instances. </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.ShapesTransparent)]
        public int ShapesTransparent { get; set; }

        /// <summary> Peak simultaneous effect objects (emitters, not particles). </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.Effects)]
        public int Effects { get; set; }

        /// <summary> Peak simultaneous text objects. </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.Texts)]
        public int Texts { get; set; }

        /// <summary> Peak simultaneously sounding audio tracks - the one count that is not an object
        /// at all. </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.Tracks)]
        public int Tracks { get; set; }

        /// <summary> Was anything ever measured into this hint? </summary>
        [JsonIgnore]
        public bool HasValue => Instances > 0 || ShapesOpaque > 0 || ShapesTransparent > 0
                                || Effects > 0 || Texts > 0 || Tracks > 0;

        public LimitHints()
        {
            Reset();
        }
        public LimitHints(int instances, int shapesOpaque, int shapesTransparent,
            int effects, int texts, int tracks)
        {
            Instances = instances;
            ShapesOpaque = shapesOpaque;
            ShapesTransparent = shapesTransparent;
            Effects = effects;
            Texts = texts;
            Tracks = tracks;
        }

        public object Clone() => Copy();
        public LimitHints Copy() =>
            new(Instances, ShapesOpaque, ShapesTransparent, Effects, Texts, Tracks);

        public void Reset()
        {
            Instances = 0;
            ShapesOpaque = 0;
            ShapesTransparent = 0;
            Effects = 0;
            Texts = 0;
            Tracks = 0;
        }

        public void Update(LimitHints src)
        {
            Instances = src.Instances;
            ShapesOpaque = src.ShapesOpaque;
            ShapesTransparent = src.ShapesTransparent;
            Effects = src.Effects;
            Texts = src.Texts;
            Tracks = src.Tracks;
        }

        public void Pull(LimitHints src)
        {
            Instances = src.Instances;
            ShapesOpaque = src.ShapesOpaque;
            ShapesTransparent = src.ShapesTransparent;
            Effects = src.Effects;
            Texts = src.Texts;
            Tracks = src.Tracks;
        }

        public override bool Equals(object obj) => obj is LimitHints value && Equals(value);
        public override int GetHashCode() => HashCode.Combine(Instances, ShapesOpaque,
            ShapesTransparent, Effects, Texts, Tracks);

        public bool Equals(LimitHints other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            var result = Instances.Equals(other.Instances)
                         && ShapesOpaque.Equals(other.ShapesOpaque)
                         && ShapesTransparent.Equals(other.ShapesTransparent)
                         && Effects.Equals(other.Effects)
                         && Texts.Equals(other.Texts)
                         && Tracks.Equals(other.Tracks);
            return result;
        }

        public override string ToString() =>
            $"instances:{Instances}, shapes_opaque:{ShapesOpaque}, " +
            $"shapes_transparent:{ShapesTransparent}, effects:{Effects}, " +
            $"texts:{Texts}, tracks:{Tracks}";
    }
}
