using System.Collections.Immutable;
using System.Text;

namespace BH.SDK.Roslyn.Modification
{
    // THE APPLY PATH IS REFLECTION-FREE BY CONSTRUCTION, which is the half of this change that
    // makes it worth doing at all rather than only correct. What it replaces looked a member up in
    // a dictionary keyed on (type, string), then went through PropertyInfo.SetValue - boxing every
    // scalar and paying a virtual dispatch per write. A case here is a type test at most, one
    // conversion and a direct assignment.
    //
    // PropertyOf IS the exception and says so: the rule-checked write needs the PropertyInfo to
    // read the [RuleXxx] attributes off, and there is no compile-time form of "every rule attribute
    // on this member" that the validation system could consume. It is built lazily, from literal
    // typeof/nameof pairs so an IL2CPP strip cannot take the members away, and it is never touched
    // by Apply.

    /// <summary> Writes ModificationTable.g.cs from the collected specs. </summary>
    internal static class ModificationTableEmitter
    {
        private const string Values = "global::BH.SDK.Utils.ModificationValues";
        private const string Property = "global::System.Reflection.PropertyInfo";

        /// <summary> The whole generated file, from specs already ordered by field id. </summary>
        public static string Emit(ImmutableArray<FieldSpec> specs, string rootType)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// Written by BH.SDK.Roslyn's ModificationTableGenerator. Do not edit.");
            builder.AppendLine();
            builder.AppendLine("namespace BH.SDK.Utils");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary> Every overridable member, addressed by its stable");
            builder.AppendLine("    /// ModificationFields number rather than by the spelling of a JSON key. </summary>");
            builder.AppendLine("    public static class ModificationTable");
            builder.AppendLine("    {");

            EmitApply(builder, specs, rootType);
            builder.AppendLine();
            EmitExists(builder, specs);
            builder.AppendLine();
            EmitIsCollection(builder, specs);
            builder.AppendLine();
            EmitPropertyOf(builder, specs);

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static void EmitApply(StringBuilder builder, ImmutableArray<FieldSpec> specs, string rootType)
        {
            builder.AppendLine("        /// <summary> Writes one override onto a materialized object.");
            builder.AppendLine("        /// False = it did not land, and why is not the caller's business. </summary>");
            builder.AppendLine($"        public static bool Apply({rootType} obj, int field, int index, object value)");
            builder.AppendLine("        {");
            builder.AppendLine("            if (obj is null) return false;");
            builder.AppendLine();
            builder.AppendLine("            switch (field)");
            builder.AppendLine("            {");

            foreach (var spec in specs)
            {
                builder.AppendLine($"                case {Hex(spec.Field)}:");
                builder.AppendLine("                {");

                var target = "obj";
                if (spec.DeclaringType != rootType)
                {
                    builder.AppendLine($"                    if (!(obj is {spec.DeclaringType} target)) return false;");
                    target = "target";
                }

                if (spec.IsCollection) EmitCollectionCase(builder, spec, target);
                else EmitScalarCase(builder, spec, target);

                builder.AppendLine("                }");
            }

            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
        }

        private static void EmitScalarCase(StringBuilder builder, FieldSpec spec, string target)
        {
            builder.AppendLine("                    if (index >= 0) return false;");
            builder.AppendLine($"                    if (!{Values}.TryConvert<{spec.PropertyType}>(value, out var converted)) return false;");
            builder.AppendLine();
            builder.AppendLine($"                    {target}.{spec.Property} = converted;");
            builder.AppendLine("                    return true;");
        }

        // An index addresses ONE element and replaces it; no index replaces the track whole. The
        // element branch refuses an index past the end rather than growing the list, because an
        // override is a divergence from a template that HAS that element - if it does not, the
        // override was written against a different template and applying it would invent content.
        private static void EmitCollectionCase(StringBuilder builder, FieldSpec spec, string target)
        {
            builder.AppendLine("                    if (index < 0)");
            builder.AppendLine("                    {");
            builder.AppendLine($"                        if (!{Values}.TryConvert<{spec.PropertyType}>(value, out var whole)) return false;");
            builder.AppendLine();
            builder.AppendLine($"                        {target}.{spec.Property} = whole;");
            builder.AppendLine("                        return true;");
            builder.AppendLine("                    }");
            builder.AppendLine();
            builder.AppendLine($"                    var list = {target}.{spec.Property};");
            builder.AppendLine("                    if (list is null || index >= list.Count) return false;");
            builder.AppendLine($"                    if (!{Values}.TryConvert<{spec.ElementType}>(value, out var element)) return false;");
            builder.AppendLine();
            builder.AppendLine("                    list[index] = element;");
            builder.AppendLine("                    return true;");
        }

        private static void EmitExists(StringBuilder builder, ImmutableArray<FieldSpec> specs)
        {
            builder.AppendLine("        /// <summary> Whether this id is a field of anything at all - what validation asks. </summary>");
            builder.AppendLine("        public static bool Exists(int field)");
            builder.AppendLine("        {");
            builder.AppendLine("            switch (field)");
            builder.AppendLine("            {");

            foreach (var spec in specs)
                builder.AppendLine($"                case {Hex(spec.Field)}:");

            builder.AppendLine("                    return true;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
        }

        private static void EmitIsCollection(StringBuilder builder, ImmutableArray<FieldSpec> specs)
        {
            builder.AppendLine("        /// <summary> Whether it is a collection, i.e. whether an index is legal on it. </summary>");
            builder.AppendLine("        public static bool IsCollection(int field)");
            builder.AppendLine("        {");
            builder.AppendLine("            switch (field)");
            builder.AppendLine("            {");

            var any = false;
            foreach (var spec in specs)
            {
                if (!spec.IsCollection) continue;

                builder.AppendLine($"                case {Hex(spec.Field)}:");
                any = true;
            }

            if (any) builder.AppendLine("                    return true;");

            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
        }

        private static void EmitPropertyOf(StringBuilder builder, ImmutableArray<FieldSpec> specs)
        {
            builder.AppendLine($"        private static global::System.Collections.Generic.Dictionary<int, {Property}> _properties;");
            builder.AppendLine();
            builder.AppendLine("        /// <summary> The property behind an id, for the rule-checked write only. Never on the apply path. </summary>");
            builder.AppendLine($"        public static {Property} PropertyOf(int field)");
            builder.AppendLine("        {");
            builder.AppendLine("            var properties = _properties;");
            builder.AppendLine("            if (properties is null)");
            builder.AppendLine("            {");
            builder.AppendLine($"                properties = new global::System.Collections.Generic.Dictionary<int, {Property}>({specs.Length})");
            builder.AppendLine("                {");

            foreach (var spec in specs)
            {
                builder.AppendLine($"                    {{ {Hex(spec.Field)}, typeof({spec.DeclaringType})"
                                   + $".GetProperty(nameof({spec.DeclaringType}.{spec.Property})) }},");
            }

            builder.AppendLine("                };");
            builder.AppendLine();
            builder.AppendLine("                _properties = properties;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return properties.TryGetValue(field, out var property) ? property : null;");
            builder.AppendLine("        }");
        }

        // Written as hex because that is how ModificationFields declares them, and a case reading
        // 0x0205 against a constant reading 0x0205 is the difference between a table a person can
        // check by eye and one they have to convert first.
        private static string Hex(int field) => "0x" + field.ToString("X4");
    }
}
