using System;
using BH.SDK.Models.Interfaces;
using BH.SDK.Rules;
using BH.SDK.Rules.Attributes;
using Newtonsoft.Json;

// ReSharper disable NonReadonlyMemberInGetHashCode

namespace BH.SDK.Models.SettingGroups
{
    /// <summary>
    /// How many objects of each kind the level needs alive at the same time, at its heaviest frame.
    /// Written by the editor on save (see LevelCapacityUtils.GetPeakUsage) so a player's game can
    /// preallocate its per-frame buffers before playback instead of growing them mid-level.
    /// <br/><br/>
    /// Strictly <b>advisory</b>: it comes from a file that may be hand-edited, generated by a third
    /// party tool, or simply stale. A consumer must treat it as a lower bound at most, recompute or
    /// grow on demand anyway, and clamp it against whatever the device actually allows. All zeroes
    /// (the default) means "no hint", not "no objects".
    /// </summary>
    [RuleContainer]
    public class LevelLimitHints : IModel<LevelLimitHints>
    {
        /// <summary> Peak count of objects of every type at once - the widest of the five. </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.Instances)]
        public int Instances { get; set; }

        /// <summary> Peak simultaneous texture objects - a subset of Instances. </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.Textures)]
        public int Textures { get; set; }

        /// <summary> Peak simultaneous effect objects (emitters, not particles). </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.Effects)]
        public int Effects { get; set; }

        /// <summary> Peak simultaneous text objects. </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.Texts)]
        public int Texts { get; set; }

        /// <summary> Peak simultaneously sounding audio tracks - the one count that is not an object
        /// at all. </summary>
        [RuleInRange(LevelRules.MinCapacityHint, LevelRules.MaxCapacityHint)]
        [JsonProperty(Names.Tracks)]
        public int Tracks { get; set; }

        /// <summary> Was anything ever measured into this hint? </summary>
        [JsonIgnore]
        public bool HasValue => Instances > 0 || Textures > 0 || Effects > 0 || Texts > 0 || Tracks > 0;

        public LevelLimitHints()
        {
            Reset();
        }
        public LevelLimitHints(int instances, int textures, int effects, int texts, int tracks)
        {
            Instances = instances;
            Textures = textures;
            Effects = effects;
            Texts = texts;
            Tracks = tracks;
        }

        public object Clone() => Copy();
        public LevelLimitHints Copy() => new(Instances, Textures, Effects, Texts, Tracks);

        public void Reset()
        {
            Instances = 0;
            Textures = 0;
            Effects = 0;
            Texts = 0;
            Tracks = 0;
        }

        public override bool Equals(object obj) => obj is LevelLimitHints value && Equals(value);
        public override int GetHashCode() => HashCode.Combine(Instances, Textures, Effects, Texts, Tracks);

        public bool Equals(LevelLimitHints other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            var result = Instances.Equals(other.Instances)
                         && Textures.Equals(other.Textures)
                         && Effects.Equals(other.Effects)
                         && Texts.Equals(other.Texts)
                         && Tracks.Equals(other.Tracks);
            return result;
        }

        public override string ToString() => $"instances:{Instances}, textures:{Textures}, " +
                                             $"effects:{Effects}, texts:{Texts}, tracks:{Tracks}";
    }
}
