using System.Text;

namespace BH.SDK.Roslyn.Validation
{
    // WHAT THIS WRITES IS THE REFLECTIVE WALK, UNROLLED. Not a tidier walk - the same one, statement
    // for statement, because the acceptance test is that the report does not change: same findings,
    // same order, same RulePath traces, on a corpus level that produces a hundred thousand of them.
    //
    // FLAT, NOT CHAINED. ModelEmitter's habit is a per-level helper calling its base FIRST; both
    // halves of that are wrong here. GetProperties is DERIVED-FIRST, so a base-first chain inverts
    // the report for every derived type and nothing stops compiling. And the walk has two phases
    // that are each total before the next begins, so a chain would have to thread every property's
    // descent gate across its boundary. Flattening costs a little duplicated code - the hierarchy is
    // two deep and the widest base has thirteen members - and buys locals instead of a pooled buffer
    // of boxed tuples.
    //
    // THE TWO PHASES ARE THE OTHER THING NOT TO TIDY. Every property's own rules run first; only
    // then does anything descend. Fusing them - check a property, immediately walk into it - is the
    // natural way to write this and it reorders the report for every object with more than one
    // walkable property, which is every RectObject. Issue order is RuleFixer's input and repairs are
    // not commutative.

    /// <summary> Writes one [RuleContainer] type's generated walk. </summary>
    internal static class ValidationEmitter
    {
        private const string Walk = "global::BH.SDK.Validations.RuleWalk";
        private const string Context = "global::BH.SDK.Rules.RuleContext";
        private const string Validatable = "global::BH.SDK.Validations.IValidatable";
        private const string Table = "global::BH.SDK.Validations.RuleTable";

        public static string Emit(ValidationSpec spec)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// Written by BH.SDK.Roslyn's ValidationGenerator. Do not edit.");
            builder.AppendLine();

            var indent = string.Empty;
            if (spec.Namespace.Length > 0)
            {
                builder.Append("namespace ").AppendLine(spec.Namespace);
                builder.AppendLine("{");
                indent = "    ";
            }

            builder.Append(indent).Append(spec.Accessibility)
                .Append(spec.IsSealed ? " sealed" : "")
                .Append(" partial class ").Append(spec.Name)
                // Declared on the generated half rather than in the source: implementing it is what
                // the generator DOES, and a type saying so in its own file would be a claim it does
                // not keep on its own. BHS1107 refuses a hand-written one for the same reason.
                .Append(" : ").AppendLine(Validatable);
            builder.Append(indent).AppendLine("{");

            var body = indent + "    ";
            EmitTable(builder, body, spec);
            builder.AppendLine();
            EmitValidate(builder, body, spec);

            builder.Append(indent).AppendLine("}");
            if (spec.Namespace.Length > 0) builder.AppendLine("}");

            return builder.ToString();
        }

        // THE ORDINAL CONTRACT, WRITTEN OUT. The names are what this generator believed the walked
        // property list to be; RuleTable re-derives it by reflection and throws when the two
        // disagree, which is the one failure mode a generated walk has that a reflective one cannot.
        // A stale BH.SDK.Roslyn.dll is by far the likeliest cause, and the message says so.

        private static void EmitTable(StringBuilder builder, string indent, ValidationSpec spec)
        {
            builder.Append(indent).Append("private static readonly ").Append(Table)
                .AppendLine(" __ValidationTable =");
            builder.Append(indent).Append("    ").Append(Table).Append(".For(typeof(")
                .Append(spec.Name).Append("), ")
                .Append(spec.HasObjectRules ? "true" : "false").AppendLine(", new string[]");
            builder.Append(indent).AppendLine("    {");

            foreach (var property in spec.Properties)
            {
                builder.Append(indent).Append("        \"")
                    .Append(property.Owner).Append('.').Append(property.Name).AppendLine("\",");
            }

            builder.Append(indent).AppendLine("    });");
        }

        private static void EmitValidate(StringBuilder builder, string indent, ValidationSpec spec)
        {
            builder.Append(indent).Append("void ").Append(Validatable).Append(".Validate(")
                .Append(Walk).Append(" walk, ").Append(Context).AppendLine(" context)");
            builder.Append(indent).AppendLine("{");

            var body = indent + "    ";
            var needsTable = spec.HasObjectRules || AnyRules(spec);
            var needsProperties = AnyWalkable(spec);

            if (needsTable) builder.Append(body).AppendLine("var table = __ValidationTable;");
            if (needsProperties)
            {
                builder.Append(body)
                    .AppendLine("var properties = __ValidationTable.Properties;");
            }

            if (spec.IsFrameScope)
            {
                builder.Append(body).AppendLine(
                    "// Entering a scope of its own rebases everything scope-relative - frames");
                builder.Append(body).AppendLine(
                    "// against its own timeline, parent ids against its own reserved targets.");
                builder.Append(body).AppendLine("context = context.WithScope(this);");
            }

            if (spec.HasObjectRules)
            {
                builder.Append(body).AppendLine(
                    "// Before every property, so a finding spanning two of them lands ahead of both.");
                builder.Append(body).AppendLine("walk.ObjectRules(table, this, context);");
            }

            EmitPhaseA(builder, body, spec);
            EmitPhaseB(builder, body, spec);

            builder.Append(indent).AppendLine("}");
        }

        private static void EmitPhaseA(StringBuilder builder, string indent, ValidationSpec spec)
        {
            var wrote = false;

            for (var i = 0; i < spec.Properties.Length; i++)
            {
                var property = spec.Properties[i];

                // Nothing to check and nowhere to descend: the reflective walk does not even read
                // such a property, and neither does this. 114 of 799 are in this state.
                if (!property.HasRules && !property.Walkable) continue;

                if (!wrote)
                {
                    builder.Append(indent).AppendLine(
                        "// PHASE A - every property's own rules, in GetProperties order, and no");
                    builder.Append(indent).AppendLine(
                        "// descent at all. Fusing this with phase B below reorders the report.");
                    wrote = true;
                }

                if (property.Walkable)
                {
                    builder.Append(indent).Append("var value").Append(i).Append(" = this.")
                        .Append(property.Name).AppendLine(";");
                }

                if (property.HasRules)
                {
                    builder.Append(indent);
                    if (property.Walkable) builder.Append("var descend").Append(i).Append(" = ");

                    builder.Append("walk.Check(table, ").Append(i).Append(", ")
                        .Append(property.Walkable ? "value" + i : "this." + property.Name)
                        .AppendLine(", context);");
                }
                else
                {
                    // No rules means nothing can fail, so the descent gate is the null check alone -
                    // which is exactly what Check would have returned. The trace segment it would
                    // have pushed and popped around an empty rule loop is unobservable.
                    builder.Append(indent).Append("var descend").Append(i).Append(" = value")
                        .Append(i).AppendLine(" != null;");
                }
            }
        }

        private static void EmitPhaseB(StringBuilder builder, string indent, ValidationSpec spec)
        {
            var wrote = false;

            for (var i = 0; i < spec.Properties.Length; i++)
            {
                var property = spec.Properties[i];
                if (!property.Walkable) continue;

                if (!wrote)
                {
                    builder.AppendLine();
                    builder.Append(indent).AppendLine(
                        "// PHASE B - the descent, as a SECOND pass in the same property order.");
                    wrote = true;
                }

                builder.Append(indent).Append("if (descend").Append(i).Append(") walk.")
                    .Append(Method(property.Shape)).Append("(properties[").Append(i).Append("], value")
                    .Append(i).AppendLine(", context);");
            }
        }

        private static string Method(DescentShape shape)
        {
            switch (shape)
            {
                case DescentShape.List: return "DescendList";
                case DescentShape.Dictionary: return "DescendDictionary";
                case DescentShape.Array: return "DescendArray";
                case DescentShape.One: return "DescendOne";
                default: return "Descend";
            }
        }

        private static bool AnyRules(ValidationSpec spec)
        {
            foreach (var property in spec.Properties)
                if (property.HasRules)
                    return true;
            return false;
        }

        private static bool AnyWalkable(ValidationSpec spec)
        {
            foreach (var property in spec.Properties)
                if (property.Walkable)
                    return true;
            return false;
        }
    }
}
