using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace BH.SDK.Roslyn
{
    /// <summary>
    /// Probe generator: emits one internal static class into EVERY assembly it is attached to.
    /// The emitted constants are read back from Unity, so "the file compiles" is the proof that
    /// the generator ran; the counts prove it saw the real compilation rather than an empty one.
    /// </summary>
    [Generator]
    public sealed class SandboxProbeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var facts = context.CompilationProvider.Select(static (compilation, _) =>
            {
                var assembly = compilation.AssemblyName ?? "<unknown>";
                var trees = compilation.SyntaxTrees.Count();
                var references = compilation.References.Count();
                return (assembly, trees, references);
            });

            context.RegisterSourceOutput(facts, static (productionContext, fact) =>
            {
                var source = new StringBuilder()
                    .AppendLine("// <auto-generated/> BulletHeroSDK.Roslyn probe")
                    .AppendLine("namespace BH.SDK.Roslyn.Generated")
                    .AppendLine("{")
                    .AppendLine("    internal static class RoslynSandboxStamp")
                    .AppendLine("    {")
                    .AppendLine($"        public const string Assembly = \"{fact.assembly}\";")
                    .AppendLine($"        public const int SyntaxTrees = {fact.trees};")
                    .AppendLine($"        public const int References = {fact.references};")
                    .AppendLine("    }")
                    .AppendLine("}")
                    .ToString();

                productionContext.AddSource("RoslynSandboxStamp.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }
    }
}
