using System.Text;

namespace BH.SDK.Roslyn.Model
{
    // WHAT THIS WRITES IS WHAT 205 FILES USED TO WRITE BY HAND, shape for shape. It is deliberately
    // not a tidier design: Update and Pull stay OVERLOADS rather than overrides, Copy stays virtual,
    // a polymorphic variant's interface-typed Update stays a no-op on a sibling. All three are
    // documented behaviour that ModelHierarchyTests pins, so reproducing them exactly is the whole
    // acceptance criterion - a "better" shape here would be a silent behaviour change in 205 types
    // at once.
    //
    // THREE CHAIN HELPERS ARE WHY THIS WORKS AT ANY DEPTH. A generator sees a type's DIRECT base and
    // nothing above it, so every helper covers its own members and calls its base's first:
    // ResetFromX, CopyToX, EqualsX. Reset() then allocates exactly one defaults instance no matter
    // how deep the hierarchy is, instead of one per level.

    /// <summary> Writes one model's generated half. </summary>
    internal static class ModelEmitter
    {
        private const string Interfaces = "global::BH.SDK.Models.Interfaces";
        private const string Utils = "global::BH.SDK.Utils.ModelUtils";
        private const string Comparer = "global::System.Collections.Generic.EqualityComparer";

        public static string Emit(ModelSpec spec)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// Written by BH.SDK.Roslyn's ModelGenerator. Do not edit.");
            builder.AppendLine("#pragma warning disable CS0109 // 'new' on a member that hides nothing");
            builder.AppendLine();

            var indent = string.Empty;
            if (spec.Namespace.Length > 0)
            {
                builder.Append("namespace ").AppendLine(spec.Namespace);
                builder.AppendLine("{");
                indent = "    ";
            }

            builder.Append(indent).Append(spec.Accessibility)
                .Append(spec.IsSealed ? " sealed" : spec.IsAbstract ? " abstract" : "")
                .Append(" partial class ").Append(spec.Name)
                // Declared on the generated half rather than on the source: implementing it is
                // what the generator DOES, so a model saying so in its own file would be a claim
                // it does not keep on its own.
                .Append(" : global::BH.SDK.Serialization.Blob.IBinaryModel")
                .AppendLine(", global::BH.SDK.Serialization.Json.IJsonModel");
            builder.Append(indent).AppendLine("{");

            var body = indent + "    ";
            EmitHooks(builder, body, spec);
            EmitReset(builder, body, spec);
            EmitCopy(builder, body, spec);
            EmitUpdate(builder, body, spec);
            EmitPull(builder, body, spec);
            EmitEquality(builder, body, spec);
            builder.AppendLine();
            ModelBlobEmitter.Emit(builder, body, spec);
            builder.AppendLine();
            ModelJsonEmitter.Emit(builder, body, spec);

            builder.Append(indent).AppendLine("}");
            if (spec.Namespace.Length > 0) builder.AppendLine("}");

            return builder.ToString();
        }

        #region Sections

        private static void EmitHooks(StringBuilder builder, string indent, ModelSpec spec)
        {
            builder.Append(indent).AppendLine("#region Generated model contract");
            builder.AppendLine();
            builder.Append(indent).AppendLine("// Hooks. An undeclared partial method is removed by");
            builder.Append(indent).AppendLine("// the compiler whole, call included, so an unused one");
            builder.Append(indent).AppendLine("// costs nothing. Each fires for THIS type's own half:");
            builder.Append(indent).AppendLine("// a base's hook runs from the base's own body.");
            builder.Append(indent).AppendLine("partial void OnReset();");
            builder.Append(indent).Append("partial void OnCopied(").Append(spec.Name).AppendLine(" copy);");
            builder.Append(indent).Append("partial void OnUpdated(").Append(spec.Name).AppendLine(" src);");
            builder.Append(indent).Append("partial void OnPulled(").Append(spec.Name).AppendLine(" src);");
            builder.AppendLine();
        }

        private static void EmitReset(StringBuilder builder, string indent, ModelSpec spec)
        {
            var helper = "ResetFrom" + spec.Name;

            builder.Append(indent).AppendLine("/// <summary> Back to what the constructor builds. </summary>");
            if (spec.IsAbstract)
            {
                // Nothing to build a defaults instance from. The subtype's Reset() allocates one of
                // its own concrete type and reaches this type's half through the chain helper.
                builder.Append(indent).AppendLine("public abstract void Reset();");
                builder.AppendLine();
                EmitResetHelper(builder, indent, spec);
                return;
            }

            builder.Append(indent).Append("public ").Append(Modifier(spec)).AppendLine("void Reset()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    // The constructor is the single source of every default, so they are");
            builder.Append(indent).AppendLine("    // read from a fresh instance rather than restated. One instance for the");
            builder.Append(indent).AppendLine("    // whole chain, and a fresh one each time - LevelMeta's constructor draws");
            builder.Append(indent).AppendLine("    // a new LevelId, which a shared prototype would hand out over and over.");
            builder.Append(indent).Append("    var defaults = new ").Append(spec.Name).AppendLine("();");
            builder.Append(indent).Append("    ").Append(helper).AppendLine("(defaults);");
            builder.Append(indent).AppendLine("    OnReset();");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            EmitResetHelper(builder, indent, spec);
        }

        private static void EmitResetHelper(StringBuilder builder, string indent, ModelSpec spec)
        {
            builder.Append(indent).Append(HelperAccess(spec)).Append("void ").Append("ResetFrom")
                .Append(spec.Name).Append('(').Append(spec.Name).AppendLine(" defaults)");
            builder.Append(indent).AppendLine("{");
            if (spec.BaseModel != null)
                builder.Append(indent).Append("    ResetFrom").Append(SimpleName(spec.BaseModel))
                    .AppendLine("(defaults);");

            foreach (var member in spec.Members)
            {
                if (!member.Assignable) continue;
                builder.Append(indent).Append("    ").AppendLine(ResetMember(member));
            }

            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
        }

        private static void EmitCopy(StringBuilder builder, string indent, ModelSpec spec)
        {
            var helper = "CopyTo" + spec.Name;
            var copyReturn = spec.BaseModel ?? spec.Name;

            if (spec.IsAbstract)
            {
                builder.Append(indent).AppendLine("public abstract object Clone();");
                builder.Append(indent).Append("public abstract ").Append(copyReturn).AppendLine(" Copy();");
                builder.AppendLine();
                EmitCopyHelper(builder, indent, spec);
                return;
            }

            builder.Append(indent).Append("public ").Append(Modifier(spec)).AppendLine("object Clone() => CopyImpl();");
            builder.Append(indent).Append("public ").Append(Modifier(spec)).Append(copyReturn)
                .AppendLine(" Copy() => CopyImpl();");

            // A subclass cannot overload Copy() on its return type, so the strongly typed answer is
            // the interface's own - the same explicit implementation the hand-written code carried.
            if (spec.BaseModel != null)
                builder.Append(indent).Append(spec.Name).Append(' ').Append(Interfaces)
                    .Append(".ICopyable<").Append(spec.Name).AppendLine(">.Copy() => CopyImpl();");

            foreach (var family in spec.Families)
                builder.Append(indent).Append(family.InterfaceType).Append(' ').Append(Interfaces)
                    .Append(".ICopyable<").Append(family.InterfaceType).AppendLine(">.Copy() => CopyImpl();");

            builder.AppendLine();
            builder.Append(indent).Append("private ").Append(spec.Name).AppendLine(" CopyImpl()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    var copy = new ").Append(spec.Name).AppendLine("();");
            builder.Append(indent).Append("    ").Append(helper).AppendLine("(copy);");
            builder.Append(indent).AppendLine("    OnCopied(copy);");
            builder.Append(indent).AppendLine("    return copy;");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            EmitCopyHelper(builder, indent, spec);
        }

        private static void EmitCopyHelper(StringBuilder builder, string indent, ModelSpec spec)
        {
            builder.Append(indent).Append(HelperAccess(spec)).Append("void ").Append("CopyTo")
                .Append(spec.Name).Append('(').Append(spec.Name).AppendLine(" copy)");
            builder.Append(indent).AppendLine("{");
            if (spec.BaseModel != null)
                builder.Append(indent).Append("    CopyTo").Append(SimpleName(spec.BaseModel))
                    .AppendLine("(copy);");

            foreach (var member in spec.Members)
            {
                if (!member.Assignable) continue;
                builder.Append(indent).Append("    copy.").Append(member.Name).Append(" = ")
                    .Append(CopyExpression(member, "this.")).AppendLine(";");
            }

            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
        }

        private static void EmitUpdate(StringBuilder builder, string indent, ModelSpec spec)
        {
            builder.Append(indent).AppendLine("/// <summary> Become src, replacing every nested instance. </summary>");
            builder.Append(indent).Append("public void Update(").Append(spec.Name).AppendLine(" src)");
            builder.Append(indent).AppendLine("{");
            if (spec.BaseModel != null) builder.Append(indent).AppendLine("    base.Update(src);");

            foreach (var member in spec.Members)
            {
                if (!member.Assignable) continue;
                builder.Append(indent).Append("    ").Append(member.Name).Append(" = ")
                    .Append(CopyExpression(member, "src.")).AppendLine(";");
            }

            builder.Append(indent).AppendLine("    OnUpdated(src);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            foreach (var family in spec.Families)
            {
                builder.Append(indent).Append("// A no-op on a sibling variant, deliberately: a ")
                    .Append(spec.Name).AppendLine(" cannot become one.");
                builder.Append(indent).Append("void ").Append(Interfaces).Append(".IUpdatable<")
                    .Append(family.InterfaceType).Append(">.Update(").Append(family.InterfaceType)
                    .AppendLine(" src)");
                builder.Append(indent).AppendLine("{");
                builder.Append(indent).Append("    if (src is ").Append(spec.Name)
                    .AppendLine(" value) Update(value);");
                builder.Append(indent).AppendLine("}");
                builder.AppendLine();
            }
        }

        private static void EmitPull(StringBuilder builder, string indent, ModelSpec spec)
        {
            builder.Append(indent).AppendLine("/// <summary> Become src without invalidating anything pointing inside. </summary>");
            builder.Append(indent).Append("public void Pull(").Append(spec.Name).AppendLine(" src)");
            builder.Append(indent).AppendLine("{");
            if (spec.BaseModel != null) builder.Append(indent).AppendLine("    base.Pull(src);");

            foreach (var member in spec.Members)
            {
                if (!member.Assignable) continue;
                builder.Append(indent).Append("    ").AppendLine(PullStatement(member));
            }

            builder.Append(indent).AppendLine("    OnPulled(src);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            foreach (var family in spec.Families)
            {
                builder.Append(indent).Append("void ").Append(Interfaces).Append(".IMoveable<")
                    .Append(family.InterfaceType).Append(">.Pull(").Append(family.InterfaceType)
                    .AppendLine(" src)");
                builder.Append(indent).AppendLine("{");
                builder.Append(indent).Append("    if (src is ").Append(spec.Name)
                    .AppendLine(" value) Pull(value);");
                builder.Append(indent).AppendLine("}");
                builder.AppendLine();
            }
        }

        private static void EmitEquality(StringBuilder builder, string indent, ModelSpec spec)
        {
            var helper = "Equals" + spec.Name;

            builder.Append(indent).Append("public override bool Equals(object obj) => obj is ")
                .Append(spec.Name).AppendLine(" value && Equals(value);");
            builder.AppendLine();

            builder.Append(indent).AppendLine("public override int GetHashCode()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    var hash = new global::System.HashCode();");
            if (spec.BaseModel != null) builder.Append(indent).AppendLine("    hash.Add(base.GetHashCode());");
            foreach (var member in spec.Members)
            {
                if (!member.Assignable) continue;
                builder.Append(indent).Append("    ").AppendLine(HashStatement(member));
            }
            builder.Append(indent).AppendLine("    return hash.ToHashCode();");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            // The strongly typed one. Virtual only at the root of an open hierarchy, since that is
            // the signature a subclass overrides; a subclass declares its OWN typed overload beside
            // the override below.
            var typed = spec.BaseModel == null && !spec.IsSealed ? "virtual " : string.Empty;
            builder.Append(indent).Append("public ").Append(typed).Append("bool Equals(")
                .Append(spec.Name).AppendLine(" other)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (other is null) return false;");
            builder.Append(indent).AppendLine("    if (ReferenceEquals(this, other)) return true;");
            builder.Append(indent).Append("    return ").Append(helper).AppendLine("(other);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            if (spec.BaseModel != null)
            {
                var baseName = SimpleName(spec.BaseModel);
                builder.Append(indent).AppendLine("// Through a base reference a sibling subtype DOWNGRADES to the");
                builder.Append(indent).AppendLine("// shared half rather than answering false - documented behaviour");
                builder.Append(indent).AppendLine("// the hand-written code had, and what Equals(object) does not do.");
                builder.Append(indent).Append("public override bool Equals(").Append(spec.BaseModel)
                    .AppendLine(" other)");
                builder.Append(indent).AppendLine("{");
                builder.Append(indent).AppendLine("    if (other is null) return false;");
                builder.Append(indent).AppendLine("    if (ReferenceEquals(this, other)) return true;");
                builder.Append(indent).Append("    return other is ").Append(spec.Name)
                    .Append(" value ? ").Append(helper).Append("(value) : Equals").Append(baseName)
                    .AppendLine("(other);");
                builder.Append(indent).AppendLine("}");
                builder.AppendLine();
            }

            foreach (var family in spec.Families)
            {
                builder.Append(indent).Append("public bool Equals(").Append(family.InterfaceType)
                    .Append(" other) => other is ").Append(spec.Name).AppendLine(" value && Equals(value);");
            }
            if (!spec.Families.IsEmpty) builder.AppendLine();

            builder.Append(indent).Append(HelperAccess(spec)).Append("bool ").Append(helper)
                .Append('(').Append(spec.Name).AppendLine(" other)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    return true");
            if (spec.BaseModel != null)
                builder.AppendLine().Append(indent).Append("        && Equals")
                    .Append(SimpleName(spec.BaseModel)).Append("(other)");
            foreach (var member in spec.Members)
            {
                if (!member.Assignable) continue;
                builder.AppendLine().Append(indent).Append("        && ").Append(EqualsExpression(member));
            }
            builder.AppendLine(";");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            builder.Append(indent).AppendLine("#endregion");
        }

        #endregion

        #region Member expressions

        // RESET RESTORES A VALUE WITHOUT REPLACING AN INSTANCE, which is what the hand-written
        // bodies did member by member: a nested model was Reset() in place, a collection was
        // Clear()ed in place, and only a POLYMORPHIC field was replaced - a Vector2Rect cannot be
        // reset into the Vector2Value the constructor wanted. PullFrom answers both at once, since
        // it keeps the instance exactly while the concrete types allow it.
        private static string ResetMember(MemberSpec member)
        {
            var access = "defaults." + member.Name;
            switch (member.Shape)
            {
                case MemberShape.Model:
                case MemberShape.PolymorphicModel:
                    return member.Name + " = (" + member.Type + ")" + Utils + ".PullFrom("
                           + member.Name + ", " + access + ");";
                case MemberShape.ModelList:
                case MemberShape.ValueList:
                case MemberShape.ModelArray:
                case MemberShape.UnmanagedArray:
                case MemberShape.ModelDictionary:
                case MemberShape.ValueDictionary:
                    return member.Name + " = " + Utils + ".ResetTo(" + member.Name + ", " + access + ");";
                default:
                    return member.Name + " = " + access + ";";
            }
        }

        private static string CopyExpression(MemberSpec member, string source)
        {
            var access = source + member.Name;
            switch (member.Shape)
            {
                case MemberShape.Value:
                    return access;
                // The cast is not decoration: Copy() is virtual and returns the BASE model type, so
                // a member typed as a subclass (AudioReverb, TextureResource) would not assign.
                case MemberShape.Model:
                case MemberShape.PolymorphicModel:
                    return "(" + member.Type + ")(" + access + "?.Copy())";
                case MemberShape.ModelList:
                    return Utils + ".CopyList(" + access + ")";
                case MemberShape.ValueList:
                    return "new " + member.Type + "(" + access + ")";
                case MemberShape.ModelArray:
                    return Utils + ".CopyArray(" + access + ")";
                case MemberShape.UnmanagedArray:
                    return Utils + ".CopyArrayUnmanaged(" + access + ")";
                case MemberShape.ModelDictionary:
                    return Utils + (member.KeyIsModel ? ".CopyDictionaryManaged(" : ".CopyDictionary(")
                           + access + ")";
                case MemberShape.ValueDictionary:
                    return "new " + member.Type + "(" + access + ")";
                default:
                    return access;
            }
        }

        private static string PullStatement(MemberSpec member)
        {
            var access = "src." + member.Name;

            // A nested model keeps its instance while the concrete types allow it - that identity IS
            // the difference between Pull and Update, and PullFrom is the only path that gets it
            // right for a polymorphic field, where a Vector2Value cannot become a Vector2Rect.
            if (member.Shape == MemberShape.Model || member.Shape == MemberShape.PolymorphicModel)
                return member.Name + " = (" + member.Type + ")" + Utils + ".PullFrom(" + member.Name
                       + ", " + access + ");";

            if (member.MergeOnPull)
                return member.PullDispatcher is null
                    ? Utils + ".PullDictionary(" + member.Name + ", " + access + ");"
                    : Utils + ".PullDictionary(" + member.Name + ", " + access + ", "
                      + member.PullDispatcher + ");";

            return member.Name + " = " + CopyExpression(member, "src.") + ";";
        }

        private static string EqualsExpression(MemberSpec member)
        {
            var mine = member.Name;
            var theirs = "other." + member.Name;
            switch (member.Shape)
            {
                case MemberShape.ModelList:
                case MemberShape.ValueList:
                    return Utils + ".ListEquals(" + mine + ", " + theirs + ")";
                case MemberShape.ModelArray:
                case MemberShape.UnmanagedArray:
                    return Utils + ".ArrayEquals(" + mine + ", " + theirs + ")";
                case MemberShape.ModelDictionary:
                case MemberShape.ValueDictionary:
                    return Utils + ".DictionaryEquals(" + mine + ", " + theirs + ")";
                default:
                    // Uniform and null-safe, and it does not box a value type: the default comparer
                    // for a T carrying IEquatable<T> is that implementation. It is also what keeps
                    // float.NaN equal to itself here, exactly as the hand-written .Equals calls did.
                    return Comparer + "<" + member.Type + ">.Default.Equals(" + mine + ", " + theirs + ")";
            }
        }

        private static string HashStatement(MemberSpec member)
        {
            switch (member.Shape)
            {
                case MemberShape.ModelList:
                case MemberShape.ValueList:
                    return "hash.Add(" + Utils + ".GetListHashCode(" + member.Name + "));";
                case MemberShape.ModelArray:
                case MemberShape.UnmanagedArray:
                    return "hash.Add(" + Utils + ".GetArrayHashCode(" + member.Name + "));";
                case MemberShape.ModelDictionary:
                case MemberShape.ValueDictionary:
                    return "hash.Add(" + Utils + ".GetDictionaryHashCode(" + member.Name + "));";
                default:
                    return "hash.Add(" + member.Name + ");";
            }
        }

        #endregion

        #region Modifiers

        /// <summary> `virtual` on an open type, `override` under a generated base, nothing on a
        /// sealed one. Sealed is the ONLY signal used - asking "does anything derive from me" needs
        /// the whole compilation and would cost per-type caching. </summary>
        private static string Modifier(ModelSpec spec)
        {
            if (spec.BaseModel != null) return "override ";
            return spec.IsSealed ? string.Empty : "virtual ";
        }

        private static string HelperAccess(ModelSpec spec) => spec.IsSealed ? "private " : "protected ";

        private static string SimpleName(string qualified)
        {
            var index = qualified.LastIndexOf('.');
            return index < 0 ? qualified : qualified.Substring(index + 1);
        }

        #endregion
    }
}
